.TH "" "" "" "" ""
.SH org2pdf
.RS
.PP
No name given yet
.RE
.SS Install
.PP
Install it with
.IP
.nf
\f[C]
npm\ install\ org2pdf
\f[]
.fi
.SS Usage
.IP
.nf
\f[C]
Usage:
\ \ \ \ org2pdf\ \-f\ FILE
\ \ \ \ org2pdf\ (\ \-h\ |\ \-\-help\ )\ 

Options:
\ \ \ \ \-h,\ \-\-help\ \ \ \ \ \ \ \ \ \ \ \ \ \ help\ for\ org2pdf\ 
\ \ \ \ \-f,\ \-\-file\ FILE\ \ \ \ \ \ \ \ \ input\ file
\f[]
.fi
.SS Author
.IP \[bu] 2
Vittorio Zaccaria
.SS License
.PP
Released under the BSD License.
.PP
   *   *   *   *   *
